version: '3.8'
services:
  admin-dashboard:
    container_name: chat_example
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8081:80"
      # - "8443:443"
    healthcheck:
      test: [ "CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:80/ || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
